### ISSUE TITLE
query `@supports` not supported

### ISSUE THREAD

**Issue by chharvey** [sintaxi/terraform#135]
Write the following in a Less file:

```less
// styles.less
@supports (color: green) {
  h1 { color: green; }
}
```

Run `$ harp server` and load a page with `<link href="styles.css"/>` in the head. The following error is received:

    (node:63081) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): BrowserslistError: Unknown browser query `op_mini all`

See [@supports](https://developer.mozilla.org/en-US/docs/Web/CSS/@supports) for info.

This is not an issue with Less, as no error is received when compiling the Less file into CSS.
